client:
  connectivity:
    port: 8081
  timing:
    loopWaiting: 10
    sendIterationsPerTaskExecution: 3
    receiveIterationsPerTaskExecution: 3
    fileIterationsPerTaskExecution: 3
    inputReadIterationsPerTaskExecution: 3
